name              "s9y_socialcaster"
maintainer       "E Camden Fisher"
maintainer_email "fish@fishnix.net"
license          "Apache 2.0"
description      "Installs/Configures s9y-socialcaster"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.3"
depends "git"
depends "rvm"
depends "redis"